import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/footer";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "AVR Reservation System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
